name: CI Pipeline (Docker + Nginx)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Build Docker image
        run: docker build -t mydevsecops-nginx .

      - name: Run Docker container
        run: docker run -d -p 8080:80 --name nginx-test mydevsecops-nginx

      - name: Wait for container startup
        run: sleep 3

      - name: Test website with curl
        run: curl -I http://localhost:8080

      - name: Stop container
        run: docker stop nginx-test

      - name: Remove container
        run: docker rm nginx-test
