name: Docker Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mydevsecops-nginx:${{ github.sha }} .

      # --- Security Scan (Trivy) ---
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: mydevsecops-nginx:${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 0

      - name: List Docker images
        run: docker images

      # --- Run container for testing ---
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name test-container mydevsecops-nginx:${{ github.sha }}

      - name: Wait for container startup
        run: sleep 5

      - name: Test website with curl
        run: curl -I http://localhost:8080

      - name: Check page content
        run: curl -s http://localhost:8080 | grep -i "NexaPointIT"

      - name: Show container logs
        run: docker logs test-container

      - name: Stop and remove container
        run: |
          docker stop test-container
          docker rm test-container

      # --- DockerHub Push (Only main branch) ---
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image (latest)
        if: github.ref == 'refs/heads/main'
        run: docker tag mydevsecops-nginx:${{ github.sha }} hakimabdi/nexapointit-devsecops:latest

      - name: Tag Docker image (commit SHA)
        if: github.ref == 'refs/heads/main'
        run: docker tag mydevsecops-nginx:${{ github.sha }} hakimabdi/nexapointit-devsecops:${{ github.sha }}

      - name: Push Docker image (latest)
        if: github.ref == 'refs/heads/main'
        run: docker push hakimabdi/nexapointit-devsecops:latest

      - name: Push Docker image (commit SHA)
        if: github.ref == 'refs/heads/main'
        run: docker push hakimabdi/nexapointit-devsecops:${{ github.sha }}
