name: Docker Build, Test and Push

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hakimabdi/nexapointit-devsecops:latest .

      - name: Run container
        run: docker run -d -p 8080:80 --name test-container hakimabdi/nexapointit-devsecops:latest

      - name: Wait for container startup
        run: sleep 5

      - name: Test website with curl
        run: curl -I http://localhost:8080

      - name: Check page content
        run: curl -s http://localhost:8080 | grep "NexaPointIT"

      - name: Stop container
        run: docker stop test-container

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        run: docker push hakimabdi/nexapointit-devsecops:latest
